FROM debian:stretch

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.name="instantbox/debian:stretch" \
  org.label-schema.vcs-url="https://github.com/instantbox/instantbox-images" \
  maintainer="Instantbox Team <team@instantbox.org>"

WORKDIR /home

# source
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list \
  && sed -i s/security.debian.org/archive.debian.org/g /etc/apt/sources.list \
  && sed -i s/stretch-updates/stretch/g /etc/apt/sources.list

RUN apt-get update -qq && apt-get install -qq -y python3-pip python3-setuptools --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && pip3 install freeFile

ARG TARGETARCH

COPY ./ttyd_linux.$TARGETARCH /usr/bin/

RUN chmod +x /usr/bin/ttyd_linux.$TARGETARCH

CMD ["ttyd_linux.$TARGETARCH", "-p", "1588", "bash"]

EXPOSE 1588

ARG BUILD_DATE
ARG VCS_REF
LABEL \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-ref=$VCS_REF
