FROM debian:trixie

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.name="instantbox/debian:trixie" \
  org.label-schema.vcs-url="https://github.com/instantbox/instantbox-images" \
  maintainer="Instantbox Team <team@instantbox.org>"

WORKDIR /home

RUN apt-get update -qq && apt-get install -qq -y pipx --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && pipx install freeFile

ARG TARGETARCH

COPY ./ttyd_linux.$TARGETARCH /usr/bin/ttyd_linux

RUN chmod +x /usr/bin/ttyd_linux

CMD ["ttyd_linux", "-p", "1588", "bash"]

EXPOSE 1588

ARG BUILD_DATE
ARG VCS_REF
LABEL \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-ref=$VCS_REF
